export const navLinkTextArrivals = 'NEW ARRIVALS';
export const navLinkTextShop = 'SHOP';
export const navLinkTextCollections = 'COLLECTIONS';
export const navLinkTextSearch = 'SEARCH';
export const navLinkTextSignIn = 'SIGN IN';
export const navLinkTextBag = 'BAG';
export const headerTextTitle = 'NEW COLLECTION';
export const headerTextSubTitlePartOne = 'Our easiest chuck-on-and-go staples come with a serious style heritage ';
export const headerTextSubTitlePartSecond = 'that’s liberating, sexy, comfy and supremely cool.';
export const headerTextButton = 'SHOP NEW ARRIVALS';
export const sectionCategoryTitleTextPartOne = 'Shop by the ';
export const sectionCategoryTitleTextPartSecond = 'Category';
export const sectionSaleTitleTextPartOne = '#MODNIKKY';
export const sectionSaleTitleTextPartSecond = '_Sale';
export const salePercent = String(55);
export const saleBtnCardTextAdd = 'ADD TO BAG';
export const shopInstagramText = 'SHOP INSTAGRAM';
export const goToShopInstagramText = 'SHOP';
export const singUpFormFooterTitleText = 'SIGN UP FOR UPDATES';
export const singUpFormFooterSubTitleText = 'Sign up for exclusive early sale access and tailored new arrivals.';
export const singUpPlaceholderText = 'Your email address';
export const singUpBtnText = 'JOIN';
export const FooterListTextCustomer = 'CUSTOMER SERVICE';
export const FooterListTextContact = 'CONTACT';
export const FooterListTextTrack = 'TRACK ORDER';
export const FooterListTextDelivery = 'DELIVERY & RETURNS';
export const FooterListTextPayment = 'PAYMENT';
export const FooterListTextReturn = 'MAKE A RETURN';
export const FooterListTextFAQ = 'FAQ';
export const FooterListTextInfo = 'INFO';
export const FooterListTextGift = 'GIFT VOUCHERS';
export const FooterListTextSize = 'SIZE GUIDE';
export const FooterListTextCareers = 'CAREERS AT MODNIKKY';
export const FooterListTextAbout = 'ABOUT US';
export const FooterListTextPolicies = 'LEGAL POLICIES';
export const FooterListTextFollow = 'FOLLOW US';
export const FooterListTextFacebook = 'FACEBOOK';
export const FooterListTextOdnoklassniki = 'ODNOKLASSNIKI';
export const FooterListTextInstagram = 'INSTAGRAM';
export const FooterListTextContactUs = 'CONTACT US';
export const FooterListTextEmail = 'hello@modnikky.com';
export const FooterListTextTel = '+7 910 832 26XX';
export const FooterListTextVisit = 'Visit us at Shalalaeva 23,\n' + 'Bologoe, Russia';
export const ItemPageTextOrder = 'PRE-ORDER';
export const ItemPageTextColor = 'COLOR';
// export const ItemPageTextSize = 'SIZE';
export const NotFoundText = 'No beauty products found...';
export const BtnShowMoreItemCategoryText = 'Show more'




