export const CATALOG_DATA_LOAD = 'CATALOG_DATA_LOAD';
export const PRODUCT_DATA_LOAD = 'PRODUCT_DATA_LOAD';
export const SHOW_SECTION_CATEGORY = 'SHOW_SECTION_CATEGORY';
export const CURRENT_PAGE_TO_SHOW = 'CURRENT_PAGE_TO_SHOW';